### PR TITLE
S63/32

### PR DESCRIPTION
**Pull request by psalqvist**
Added front end changes to MatchListItem.js

### CODE REVIEW

**Review by halvtomat — CHANGES_REQUESTED** [review]
Solve merge conflict in App.js

**Comment by psalqvist** [comment]
> Solve merge conflict in App.js

**Review by halvtomat — APPROVED** [review]
The number one , creme de la creme, top pull request in this project so far! If all pull request were as bug free as this one, the project would have been done last week

**Comment by psalqvist** [comment]
> The number one , creme de la creme, top pull request in this project so far! If all pull request were as bug free as this one, the project would have been done last week

Thank you for the kind words halvtomat!

**Pull request merged**
